pipeline:

  test:
    image: ethicaljobs/aphex
    pull: true
    commands: [ 'composer install --prefer-dist', './vendor/bin/phpunit' ]

  notify-slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: deployments
    when:
      event: tag